### ISSUE TITLE
Create an invitation system for registration

### ISSUE THREAD

**Issue by fmoko** [tometoproject/tometo#7]
Redmine: https://bugs.marisa.cloud/issues/10

**Comment by fmoko** [comment]
In-progress branch for this: https://github.com/tometoproject/tometo/tree/invitations

Here's a rough checklist of what needs to be done:
- [ ] Backend needs to support invitations
  - [ ] Create invitations
  - [ ] Query invitations for logged in user
  - [ ] Update invitation with user that used it
  - [ ] Modify registration to only work with invitations
  - [ ] Maybe toggle the previous point for staging??
- [ ] Frontend needs to support invitations
  - [ ] Have an invitations page
  - [ ] List invitations and invitation limit
  - [ ] Allow use of invitation links
  - [ ] Integrate registration with invitations
